
export const mock = [
    {
        "resource_state": 2,
        "athlete": {
            "id": 99857526,
            "resource_state": 1
        },
        "name": "Bicicleta por la tarde",
        "distance": 25000,
        "moving_time": 3600,
        "elapsed_time": 3600,
        "total_elevation_gain": 20,
        "type": "Ride",
        "workout_type": 11,
        "id": 6788055597,
        "start_date": "2022-03-07T21:40:00Z",
        "start_date_local": "2022-03-07T13:40:00Z",
        "timezone": "(GMT-08:00) America/Los_Angeles",
        "utc_offset": -28800,
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a6788055597",
            "summary_polyline": null,
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": true,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "start_latitude": null,
        "start_longitude": null,
        "average_speed": 6.944,
        "max_speed": 0,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "upload_id": null,
        "external_id": null,
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 99857526,
            "resource_state": 1
        },
        "name": "Carrera de tarde",
        "distance": 10000,
        "moving_time": 7200,
        "elapsed_time": 7200,
        "total_elevation_gain": 7.9,
        "type": "Run",
        "workout_type": 2,
        "id": 6788094758,
        "start_date": "2022-03-02T21:50:00Z",
        "start_date_local": "2022-03-02T13:50:00Z",
        "timezone": "(GMT-08:00) America/Los_Angeles",
        "utc_offset": -28800,
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a6788094758",
            "summary_polyline": null,
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": true,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "start_latitude": null,
        "start_longitude": null,
        "average_speed": 1.389,
        "max_speed": 0,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "upload_id": null,
        "external_id": null,
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 99857526,
            "resource_state": 1
        },
        "name": "Bicicleta por la tarde",
        "distance": 16093.4,
        "moving_time": 7200,
        "elapsed_time": 7200,
        "total_elevation_gain": 7.9,
        "type": "Ride",
        "workout_type": 11,
        "id": 6788107953,
        "start_date": "2022-02-23T21:50:00Z",
        "start_date_local": "2022-02-23T13:50:00Z",
        "timezone": "(GMT-08:00) America/Los_Angeles",
        "utc_offset": -28800,
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a6788107953",
            "summary_polyline": null,
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": true,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "start_latitude": null,
        "start_longitude": null,
        "average_speed": 2.235,
        "max_speed": 0,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "upload_id": null,
        "external_id": null,
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 99857526,
            "resource_state": 1
        },
        "name": "Carrera de tarde",
        "distance": 8046.7,
        "moving_time": 3600,
        "elapsed_time": 3600,
        "total_elevation_gain": 7.9,
        "type": "Run",
        "workout_type": 1,
        "id": 6788099809,
        "start_date": "2022-02-11T21:50:00Z",
        "start_date_local": "2022-02-11T13:50:00Z",
        "timezone": "(GMT-08:00) America/Los_Angeles",
        "utc_offset": -28800,
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a6788099809",
            "summary_polyline": null,
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": true,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "start_latitude": null,
        "start_longitude": null,
        "average_speed": 2.235,
        "max_speed": 0,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "upload_id": null,
        "external_id": null,
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 99857526,
            "resource_state": 1
        },
        "name": "Carrera de tarde",
        "distance": 4828,
        "moving_time": 1800,
        "elapsed_time": 1800,
        "total_elevation_gain": 7.9,
        "type": "Run",
        "workout_type": 3,
        "id": 6788128527,
        "start_date": "2022-01-22T21:50:00Z",
        "start_date_local": "2022-01-22T13:50:00Z",
        "timezone": "(GMT-08:00) America/Los_Angeles",
        "utc_offset": -28800,
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a6788128527",
            "summary_polyline": null,
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": true,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "start_latitude": null,
        "start_longitude": null,
        "average_speed": 2.682,
        "max_speed": 0,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "upload_id": null,
        "external_id": null,
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 99857526,
            "resource_state": 1
        },
        "name": "Carrera de tarde",
        "distance": 8046.7,
        "moving_time": 3600,
        "elapsed_time": 3600,
        "total_elevation_gain": 7.9,
        "type": "Run",
        "workout_type": 3,
        "id": 6788117145,
        "start_date": "2022-01-13T21:50:00Z",
        "start_date_local": "2022-01-13T13:50:00Z",
        "timezone": "(GMT-08:00) America/Los_Angeles",
        "utc_offset": -28800,
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a6788117145",
            "summary_polyline": null,
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": true,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "start_latitude": null,
        "start_longitude": null,
        "average_speed": 2.235,
        "max_speed": 0,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "upload_id": null,
        "external_id": null,
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 99857526,
            "resource_state": 1
        },
        "name": "Carrera de mañana",
        "distance": 15000,
        "moving_time": 7200,
        "elapsed_time": 7200,
        "total_elevation_gain": 6.1,
        "type": "Run",
        "workout_type": 1,
        "id": 6791961472,
        "start_date": "2021-11-20T17:40:00Z",
        "start_date_local": "2021-11-20T09:40:00Z",
        "timezone": "(GMT-08:00) America/Los_Angeles",
        "utc_offset": -28800,
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a6791961472",
            "summary_polyline": null,
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": true,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "start_latitude": null,
        "start_longitude": null,
        "average_speed": 2.083,
        "max_speed": 0,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "upload_id": null,
        "external_id": null,
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "athlete": {
            "id": 99857526,
            "resource_state": 1
        },
        "name": "Bicicleta a la hora del almuerzo",
        "distance": 30000,
        "moving_time": 3600,
        "elapsed_time": 3600,
        "total_elevation_gain": 7.6,
        "type": "Ride",
        "workout_type": 12,
        "id": 6792386465,
        "start_date": "2021-10-29T18:20:00Z",
        "start_date_local": "2021-10-29T11:20:00Z",
        "timezone": "(GMT-08:00) America/Los_Angeles",
        "utc_offset": -25200,
        "location_city": null,
        "location_state": null,
        "location_country": null,
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a6792386465",
            "summary_polyline": null,
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": true,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "start_latitude": null,
        "start_longitude": null,
        "average_speed": 8.333,
        "max_speed": 0,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "upload_id": null,
        "external_id": null,
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    }
]